name: deploy-pages

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  deploy-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 初始化 Bunjs
      - name: Setup Bunjs
        uses: oven-sh/setup-bun@v2

      # 安装依赖
      - name: Install dependencies
        run: cd app && bun i --frozen-lockfile

      # 运行构建脚本
      - name: Build Bun
        run: cd app && bun run build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 创建 CNAME 绑定域名
          fqdn: shao.fun
          # 创建 .nojekyll 禁用 jekyll
          jekyll: false
          # 部署目录
          build_dir: app/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
